# Generated by Django 3.1.2 on 2020-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='picture',
            field=models.ImageField(blank=True, default='nothing.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='catergory',
            field=models.CharField(choices=[('AI', 'Antique Item'), ('E', 'Equipment'), ('O', 'Ornament'), ('OT', 'OTHERS')], default='OT', max_length=2, null=True),
        ),
    ]
