# Generated by Django 3.1.2 on 2020-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20201109_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='picture',
            field=models.ImageField(default='nothing.jpeg', null=True, upload_to=''),
        ),
    ]
